apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name:  ai-sno-cluster002
  name: ai-sno-cluster002
---
kind: Secret
apiVersion: v1
metadata:
  name: ai-bmh-secret
  namespace: ai-sno-cluster002
data:
  password: YWRtaW4K
  username: YWRtaW4K
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: pull-secret
  namespace: ai-sno-cluster002
data:
  .dockerconfigjson: <pull-sccrets>
type: kubernetes.io/dockerconfigjson

---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: ai-sno-cluster002
  namespace: ai-sno-cluster002
spec:
  cpuPartitioningMode: None
  clusterName: ai-sno-cluster002
  clusterImageSetNameRef: img4.17.4-x86-64-appsub
  machineNetwork:
    - cidr: 192.168.4.0/22
  networkType: OVNKubernetes
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrRj8UgTVFA1/1okryUGAdZ4kKAE0snw4CUp7lhCXAiB3HI2ynIrQQIn4ddzHkUjGU+tojvTmZnDWR5Gfi53BWNsByFUPPziH+XSp+LWWyYRIFPFpSBI22IQknywSaDs+e7KRiM/axFHVfGpuNRxQ9BYh9wO/xOhe4VAqQhs3M1geTiDKvwcaR77b0r2vNNuqD/6YlMaeYKy8rg6875K35BZgn+6RH1lqK/he2/uQWBhneVskncs5EUv9tSvTC4Tpg9F1LPHGB4CZaoOqB/N7Sb9goIRGjZwe9gsijnjuegbAJfuju2MG9AyNaD95zjU2kHB+tZ9SBijjvMvRdUauWj0PFypv3qb5/lUfMN2G4cSFuBktlV5YnfdP4jRCCakzbdedBG8A/711lE5IqUY464bw6M1f3uukSCvGpSEbmvzCrs2E3ZeUzxvdOyw/N5uUElL0Hzu+m5v9PYoh0D1ip7vxeAmOf9kb5aW3cO0Es8hVRD21EZDZmbvB19fdk770= bkpandey@Balkrishnas-MacBook-Pro.local
  nodes:
    - automatedCleaningMode: disabled
      nodeNetwork:
        config:
          dns-resolver:
            config:
              search:
                - balk.ocp.local
              server:
                - 192.168.7.126
                - 8.8.8.8
          interfaces:
            - ipv4:
                address:
                - ip: 192.168.7.11
                  prefix-length: 24
                dhcp: false
                enabled: true
              ipv6:
                enabled: false
              name: ens1s0
              state: up
              type: ethernet
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.4.1
                next-hop-interface: ens1s0
                table-id: 254
        interfaces:
          - macAddress: '00:00:00:00:00:11'
            name: ens1s0
      bmcCredentialsName:
        name: ai-bmh-secret
      ironicInspect: ''
      hostName: ai-sno-cluster002
      bootMode: UEFI
      role: master
      bootMACAddress: '00:00:00:00:00:11'
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
      cpuArchitecture: x86_64
      bmcAddress: 'redfish-virtualmedia+http://192.168.7.126:8000/redfish/v1/Systems/deed1e55-fe11-f0e5-0dd5-babb1ed1a011'
  baseDomain: balk.ocp.local
  holdInstallation: false
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  cpuArchitecture: x86_64
  pullSecretRef:
    name: pull-secret
